`timescale 1ns/1ps
`include "uBee_perf_events.svh"

module uBee_top #(
  parameter logic [31:0] RESET_VECTOR = 32'h8000_0000,
  parameter logic [31:0] MTVEC_RESET = 32'h8000_0000,
  parameter bit SHADOW_BANK_ENABLE = 1'b1,
  parameter bit MUL_ENABLE = 1'b1,
  parameter bit DIV_ENABLE = 1'b1,
  parameter bit BP_ENABLE = 1'b1,
  parameter bit DEBUG_ENABLE = 1'b1,
  parameter logic [31:0] DMEM_BASE = 32'h2000_0000,
  parameter logic [31:0] DMEM_MASK = 32'hFFFF_0000,
  parameter int unsigned BP_ENTRIES = 128,
  parameter bit BP_GSHARE = 1'b0,
  parameter int unsigned GHR_WIDTH = 5
) (
  input  logic        clk_i,
  input  logic        rst_ni,

  output logic        imem_req_valid_o,
  input  logic        imem_req_ready_i,
  output logic [31:0] imem_req_addr_o,
  input  logic        imem_rsp_valid_i,
  output logic        imem_rsp_ready_o,
  input  logic [31:0] imem_rsp_rdata_i,
  input  logic        imem_rsp_err_i,

  output logic        dmem_req_valid_o,
  input  logic        dmem_req_ready_i,
  output logic        dmem_req_write_o,
  output logic [31:0] dmem_req_addr_o,
  output logic [31:0] dmem_req_wdata_o,
  output logic [3:0]  dmem_req_wstrb_o,
  input  logic        dmem_rsp_valid_i,
  output logic        dmem_rsp_ready_o,
  input  logic [31:0] dmem_rsp_rdata_i,
  input  logic        dmem_rsp_err_i,

  input  logic        irq_software_i,
  input  logic        irq_timer_i,
  input  logic        irq_external_i,

  output logic        trace_valid_o,
  output logic [31:0] trace_pc_o,
  output logic [31:0] trace_instruction_o,
  output logic        trace_rd_write_o,
  output logic [4:0]  trace_rd_addr_o,
  output logic [31:0] trace_rd_data_o,
  output logic        trace_mem_valid_o,
  output logic        trace_mem_write_o,
  output logic [31:0] trace_mem_addr_o,
  output logic [31:0] trace_mem_wdata_o,
  output logic [3:0]  trace_mem_wstrb_o,
  output logic        trace_trap_o,
  output logic [31:0] trace_cause_o,

  output logic [31:0] dbg_fetch_pc_o,
  output logic [31:0] dbg_if_pc_o,
  output logic        dbg_if_valid_o,
  output logic [31:0] dbg_ex_pc_o,
  output logic        dbg_ex_valid_o,
  output logic [31:0] dbg_mem_pc_o,
  output logic        dbg_mem_valid_o,
  output logic [31:0] dbg_wb_pc_o,
  output logic        dbg_wb_valid_o,
  output logic        dbg_rf_we_o,
  output logic [4:0]  dbg_rf_waddr_o,
  output logic [31:0] dbg_rf_wdata_o,
  output logic [31:0] dbg_csr_mstatus_o,
  output logic [31:0] dbg_csr_mie_o,
  output logic [31:0] dbg_csr_mtvec_o,
  output logic [31:0] dbg_csr_mscratch_o,
  output logic [31:0] dbg_csr_mepc_o,
  output logic [31:0] dbg_csr_mcause_o,
  output logic [31:0] dbg_csr_mtval_o,
  output logic [31:0] dbg_csr_mip_o,
  output logic [31:0] dbg_csr_mcycle_o,
  output logic [31:0] dbg_csr_mcycleh_o,
  output logic [31:0] dbg_csr_minstret_o,
  output logic [31:0] dbg_csr_minstreth_o,

  output uBee_perf_events_t perf_events_o
);
  uBee_core #(
    .RESET_VECTOR       (RESET_VECTOR),
    .MTVEC_RESET        (MTVEC_RESET),
    .SHADOW_BANK_ENABLE (SHADOW_BANK_ENABLE),
    .MUL_ENABLE         (MUL_ENABLE),
    .DIV_ENABLE         (DIV_ENABLE),
    .BP_ENABLE          (BP_ENABLE),
    .DEBUG_ENABLE       (DEBUG_ENABLE),
    .DMEM_BASE          (DMEM_BASE),
    .DMEM_MASK          (DMEM_MASK),
    .BP_ENTRIES         (BP_ENTRIES),
    .BP_GSHARE          (BP_GSHARE),
    .GHR_WIDTH          (GHR_WIDTH)
  ) u_core (
    .clk_i             (clk_i),
    .rst_ni            (rst_ni),
    .imem_req_valid_o  (imem_req_valid_o),
    .imem_req_ready_i  (imem_req_ready_i),
    .imem_req_addr_o   (imem_req_addr_o),
    .imem_rsp_valid_i  (imem_rsp_valid_i),
    .imem_rsp_ready_o  (imem_rsp_ready_o),
    .imem_rsp_rdata_i  (imem_rsp_rdata_i),
    .imem_rsp_err_i    (imem_rsp_err_i),
    .dmem_req_valid_o  (dmem_req_valid_o),
    .dmem_req_ready_i  (dmem_req_ready_i),
    .dmem_req_write_o  (dmem_req_write_o),
    .dmem_req_addr_o   (dmem_req_addr_o),
    .dmem_req_wdata_o  (dmem_req_wdata_o),
    .dmem_req_wstrb_o  (dmem_req_wstrb_o),
    .dmem_rsp_valid_i  (dmem_rsp_valid_i),
    .dmem_rsp_ready_o  (dmem_rsp_ready_o),
    .dmem_rsp_rdata_i  (dmem_rsp_rdata_i),
    .dmem_rsp_err_i    (dmem_rsp_err_i),
    .irq_software_i    (irq_software_i),
    .irq_timer_i       (irq_timer_i),
    .irq_external_i    (irq_external_i),
    .trace_valid_o     (trace_valid_o),
    .trace_pc_o        (trace_pc_o),
    .trace_instruction_o(trace_instruction_o),
    .trace_rd_write_o  (trace_rd_write_o),
    .trace_rd_addr_o   (trace_rd_addr_o),
    .trace_rd_data_o   (trace_rd_data_o),
    .trace_mem_valid_o (trace_mem_valid_o),
    .trace_mem_write_o (trace_mem_write_o),
    .trace_mem_addr_o  (trace_mem_addr_o),
    .trace_mem_wdata_o (trace_mem_wdata_o),
    .trace_mem_wstrb_o (trace_mem_wstrb_o),
    .trace_trap_o      (trace_trap_o),
    .trace_cause_o     (trace_cause_o),
    .dbg_fetch_pc_o    (dbg_fetch_pc_o),
    .dbg_if_pc_o       (dbg_if_pc_o),
    .dbg_if_valid_o    (dbg_if_valid_o),
    .dbg_ex_pc_o       (dbg_ex_pc_o),
    .dbg_ex_valid_o    (dbg_ex_valid_o),
    .dbg_mem_pc_o      (dbg_mem_pc_o),
    .dbg_mem_valid_o   (dbg_mem_valid_o),
    .dbg_wb_pc_o       (dbg_wb_pc_o),
    .dbg_wb_valid_o    (dbg_wb_valid_o),
    .dbg_rf_we_o       (dbg_rf_we_o),
    .dbg_rf_waddr_o    (dbg_rf_waddr_o),
    .dbg_rf_wdata_o    (dbg_rf_wdata_o),
    .dbg_csr_mstatus_o (dbg_csr_mstatus_o),
    .dbg_csr_mie_o     (dbg_csr_mie_o),
    .dbg_csr_mtvec_o   (dbg_csr_mtvec_o),
    .dbg_csr_mscratch_o(dbg_csr_mscratch_o),
    .dbg_csr_mepc_o    (dbg_csr_mepc_o),
    .dbg_csr_mcause_o  (dbg_csr_mcause_o),
    .dbg_csr_mtval_o   (dbg_csr_mtval_o),
    .dbg_csr_mip_o     (dbg_csr_mip_o),
    .dbg_csr_mcycle_o  (dbg_csr_mcycle_o),
    .dbg_csr_mcycleh_o (dbg_csr_mcycleh_o),
    .dbg_csr_minstret_o(dbg_csr_minstret_o),
    .dbg_csr_minstreth_o(dbg_csr_minstreth_o),
    .perf_events_o     (perf_events_o)
  );
endmodule
