// uBee performance monitor MMIO map (TRM MONITOR chapter).
// Shared by rtl/peripheral/uBee_monitor.sv and software headers.

`define UBEE_MON_BASE_DEFAULT       32'h4000_5000

`define UBEE_MON_CTRL_OFFSET        12'h000
`define UBEE_MON_CYCLES_OFFSET      12'h004
`define UBEE_MON_RETIRED_OFFSET     12'h008
`define UBEE_MON_STALL_OFFSET       12'h00C
`define UBEE_MON_FLUSH_OFFSET       12'h010
`define UBEE_MON_BUBBLE_OFFSET      12'h014
`define UBEE_MON_HAZARD_OFFSET      12'h018
`define UBEE_MON_LOAD_USE_OFFSET    12'h01C
`define UBEE_MON_BRANCH_OFFSET      12'h020
`define UBEE_MON_BRANCH_TAKEN_OFFSET 12'h024
`define UBEE_MON_MISPREDICT_OFFSET  12'h028
`define UBEE_MON_IMEM_WAIT_OFFSET   12'h02C
`define UBEE_MON_DMEM_WAIT_OFFSET   12'h030
`define UBEE_MON_AXI_WAIT_OFFSET    12'h034
`define UBEE_MON_BUS_ERROR_OFFSET   12'h038
`define UBEE_MON_IRQ_TAKEN_OFFSET   12'h03C
`define UBEE_MON_ALU_USE_OFFSET     12'h040
`define UBEE_MON_MUL_USE_OFFSET     12'h044
`define UBEE_MON_DIV_USE_OFFSET     12'h048
`define UBEE_MON_CAPABILITY_OFFSET  12'h04C
`define UBEE_MON_LOAD_COUNT_OFFSET  12'h050
`define UBEE_MON_STORE_COUNT_OFFSET 12'h054
`define UBEE_MON_BRANCH_STALL_OFFSET 12'h058
`define UBEE_MON_MEM_WAIT_TOTAL_OFFSET 12'h05C
`define UBEE_MON_PREDICT_CORRECT_OFFSET 12'h060
`define UBEE_MON_SPEC_REDIRECT_OFFSET 12'h064

`define UBEE_MON_SHADOW_BIAS        12'h100

`define UBEE_MON_CTRL_ENABLE        0
`define UBEE_MON_CTRL_FREEZE        1
`define UBEE_MON_CTRL_CLEAR         2
`define UBEE_MON_CTRL_SNAPSHOT      3

// Live counter indices (CAPABILITY is not a counter).
`define UBEE_MON_CNT_CYCLES         0
`define UBEE_MON_CNT_RETIRED        1
`define UBEE_MON_CNT_STALL          2
`define UBEE_MON_CNT_FLUSH          3
`define UBEE_MON_CNT_BUBBLE         4
`define UBEE_MON_CNT_HAZARD         5
`define UBEE_MON_CNT_LOAD_USE       6
`define UBEE_MON_CNT_BRANCH         7
`define UBEE_MON_CNT_BRANCH_TAKEN   8
`define UBEE_MON_CNT_MISPREDICT     9
`define UBEE_MON_CNT_IMEM_WAIT      10
`define UBEE_MON_CNT_DMEM_WAIT      11
`define UBEE_MON_CNT_AXI_WAIT       12
`define UBEE_MON_CNT_BUS_ERROR      13
`define UBEE_MON_CNT_IRQ_TAKEN      14
`define UBEE_MON_CNT_ALU_USE        15
`define UBEE_MON_CNT_MUL_USE        16
`define UBEE_MON_CNT_DIV_USE        17
`define UBEE_MON_CNT_LOAD_COUNT     18
`define UBEE_MON_CNT_STORE_COUNT    19
`define UBEE_MON_CNT_BRANCH_STALL   20
`define UBEE_MON_CNT_MEM_WAIT_TOTAL 21
`define UBEE_MON_CNT_PREDICT_CORRECT 22
`define UBEE_MON_CNT_SPEC_REDIRECT  23
`define UBEE_MON_NUM_COUNTERS       24

// CAPABILITY [31:16] feature bits (revision 2).
`define UBEE_MON_CAP_BASE           16'h0001
`define UBEE_MON_CAP_FLUSH_HAZARD   16'h0002
`define UBEE_MON_CAP_BRANCH         16'h0004
`define UBEE_MON_CAP_IMEM           16'h0008
`define UBEE_MON_CAP_DMEM           16'h0010
`define UBEE_MON_CAP_AXI            16'h0020
`define UBEE_MON_CAP_BUS_ERROR      16'h0040
`define UBEE_MON_CAP_IRQ            16'h0080
`define UBEE_MON_CAP_EXEC_UNIT      16'h0100
`define UBEE_MON_CAP_LOAD_STORE     16'h0200
`define UBEE_MON_CAP_BRANCH_STALL   16'h0400
`define UBEE_MON_CAP_SNAPSHOT       16'h0800
`define UBEE_MON_CAP_MEM_WAIT_TOTAL 16'h1000
`define UBEE_MON_CAP_PREDICTOR      16'h2000
`define UBEE_MON_CAP_SPEC_REDIRECT  16'h4000

`define UBEE_MON_CAP_WIDTH_BITS     8'd32
`define UBEE_MON_MAP_REVISION       8'd2
